# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [2]:
import numpy as np
n=6*np.ones((5,5),dtype=int)
n[1:-1,1:-1]=0
print(n)

[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [12]:


import numpy as np 
def printcheckboard(n): 
    final = [] 
    for i in range(n): 
        final.append(list(np.tile([3,9],int(n/2))) if i%2==0 else list(np.tile([9,3],int(n/2)))) 
    print(np.array(final)) 


n = 8
printcheckboard(n) 


[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [17]:
empty_array=np.empty((3,4),dtype=float,order='C')
full_array=np.full((3,3),6)
print(empty_array,"\n",full_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [3]:
n=np.array([0,12,45.21,34,99.91])
def cel(x):
    return (5/9.0)*(x-32)
print("Expected OutputValues in Fahrenheit degrees-\n",n)
print("Values in Centigrade degrees-\n",cel(n))

Expected OutputValues in Fahrenheit degrees-
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees-
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [2]:
import numpy as np
n=np.array([ 1.00000000+0.j,0.70710678+0.70710678j],dtype=complex)
print("REAL PART OF THE ARRAY-\n",n.real)
print("IMAGINARY PART OF THE ARRAY-\n",n.imag)

REAL PART OF THE ARRAY-
 [1.         0.70710678]
IMAGINARY PART OF THE ARRAY-
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [26]:

a=np.array([0,10,20,40,60])
b=np.array([0,40])
print(np.isin(a,b))

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [27]:
a=np.array([0,10,20,40,60])
b=np.array([10,30,40])
m=np.isin(a,b)
print(a[m])

[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [28]:
l1=np.array([10,10,20,20,20,30])
l2=np.array([[1,1],[2,3]])
print("INIQUE ELEMENTS OF THE ABOVE ARRAY ARE-",np.unique(l1))
print("UNIQUE ELEMENTS OF THE ABOVE ARRAY ARE-",np.unique(l2))

INIQUE ELEMENTS OF THE ABOVE ARRAY ARE- [10 20 30]
UNIQUE ELEMENTS OF THE ABOVE ARRAY ARE- [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [1]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))


Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [10]:
n=np.array([[1,0],[3,4],[0,8]],dtype=bool)
m=np.array([1,2,3,4,5,6,7,8,9,10],dtype=bool)
print(np.all(n))
print(np.all(m))

False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [2]:
n=np.array([[1,0],[3,4],[0,8]],dtype=bool)
m=np.array([1,2,3,4,5,6,7,8,9,10],dtype=bool)
print(np.any(n))
print(np.any(m))

True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [3]:
n=np.array([1,2,3,4])
print("ORIGINAL ARRAY\n",n)
n1=np.tile(n, 2)

print("REPEATED TWO TIMES\n",n1)
n2=np.tile(n, 3)

print("REPEATED THREE TIMES\n",n2)

ORIGINAL ARRAY
 [1 2 3 4]
REPEATED TWO TIMES
 [1 2 3 4 1 2 3 4]
REPEATED THREE TIMES
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [29]:
n=np.array([1,2,3,4,5,6])
print("\t INDEX OF MAXIMUM AND MINIMUM VALUES\nMAXIMUM VALUES-",np.argmax(n),"\nMINIMUM VALUES-",np.argmin(n))

	 INDEX OF MAXIMUM AND MINIMUM VALUES
MAXIMUM VALUES- 5 
MINIMUM VALUES- 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [31]:
a=np.array([1,2])
b=np.array([4,5])
print("a>b\n",np.array(a>b,dtype=bool))
print("a>=b\n",np.array(a>=b,dtype=bool))
print("a<b\n",np.array(a<b,dtype=bool))
print("a<=b\n",np.array(a<=b,dtype=bool))

a>b
 [False False]
a>=b
 [False False]
a<b
 [ True  True]
a<=b
 [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [9]:
import numpy as np
n=np.array([[4,6],[2,1]])
print("SORTING ALONG THE FIRST AXIS\n",(np.sort(n,axis=0)))
print("SORTING ALONG THE LAST AXIS\n",np.sort(n,axis=1)[::-1])

SORTING ALONG THE FIRST AXIS
 [[2 1]
 [4 6]]
SORTING ALONG THE LAST AXIS
 [[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [11]:
first_names=np.array([ "Betsey", "Shelley", "Lanell", "Genesis", "Margery"] )
last_names =np.array( ["Battle", "Brien", "Plotner", "Stahl", "Woolum"] )
print(np.argsort(first_names))
print(np.argsort(last_names))

[0 3 2 4 1]
[0 1 2 3 4]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [12]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array- ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Original array- 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [13]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))


128 bytes


## Great Job!